[package]
name        = "yazi-widgets"
version     = "25.5.31"
edition     = "2024"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi user interface widgets"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-codegen = { path = "../yazi-codegen", version = "25.5.31" }
yazi-config  = { path = "../yazi-config", version = "25.5.31" }
yazi-macro   = { path = "../yazi-macro", version = "25.5.31" }
yazi-plugin  = { path = "../yazi-plugin", version = "25.5.31" }
yazi-proxy   = { path = "../yazi-proxy", version = "25.5.31" }
yazi-shared  = { path = "../yazi-shared", version = "25.5.31" }

# External dependencies
crossterm     = { workspace = true }
futures       = { workspace = true }
ratatui       = { workspace = true }
unicode-width = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
crossterm = { workspace = true, features = [ "use-dev-tty", "libc" ] }
