[package]
name        = "yazi-codegen"
version     = "25.12.29"
edition     = "2024"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi code generator"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
# External dependencies
syn   = { version = "2.0.112", features = [ "full" ] }
quote = "1.0.42"
