[package]
name        = "yazi-codegen"
version     = "25.2.26"
edition     = "2021"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi codegen"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[lib]
proc-macro = true

[dependencies]
# External dependencies
syn   = { version = "2.0.98", features = [ "full" ] }
quote = "1.0.38"
