[package]
name        = "yazi-codegen"
version     = "25.5.31"
edition     = "2024"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi code generator"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[lib]
proc-macro = true

[dependencies]
# External dependencies
syn   = { version = "2.0.101", features = [ "full" ] }
quote = "1.0.40"
