[tab]
active    = { fg = "#1E2031", bg = "#80AEFA" }
inactive  = { fg = "#C8D3F8", bg = "#484D66" }
max_width = 1

[status]
primary	  = { normal = "#80AEFA", select = "#CD9EFC", unset = "#FFA577" }
secondary = { normal = "#1E2031", select = "#23273B", unset = "#23273B" }
tertiary  = { normal = "#6D738F", select = "#6D738F", unset = "#6D738F" }
body      = { normal = "#484D66", select = "#484D66", unset = "#484D66" }
emphasis  = { normal = "#C8D3F8", select = "#C8D3F8", unset = "#C8D3F8" }
info      = { normal = "#7AD9E5", select = "#7AD9E5", unset = "#7AD9E5" }
success   = { normal = "#97DC8D", select = "#97DC8D", unset = "#97DC8D" }
warning   = { normal = "#F3D398", select = "#F3D398", unset = "#F3D398" }
danger    = { normal = "#FA7F94", select = "#FA7F94", unset = "#FA7F94" }
separator = { opening = "", closing = "" }

[progress]
gauge = { fg = "#FFA577", bg = "#484D66" }
label = { fg = "#FFFFFF", bold = true }

[selection]
hovered = { fg = "#1E2031", bg = "#80AEFA" }

[marker]
selecting = { fg = "#97DC8D", bg = "#97DC8D" }
selected  = { fg = "#F3D398", bg = "#F3D398" }

[preview]
hovered       = { underline = true }
syntect_theme = "~/.config/bat/themes/Catppuccin-macchiato.tmTheme"

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#7AD9E5" },

	# Videos
	{ mime = "video/*", fg = "#F3D398" },
	{ mime = "audio/*", fg = "#F3D398" },

	# Archives
	{ mime = "application/zip", fg = "#CD9EFC" },
	{ mime = "application/gzip", fg = "#CD9EFC" },
	{ mime = "application/x-tar", fg = "#CD9EFC" },
	{ mime = "application/x-bzip", fg = "#CD9EFC" },
	{ mime = "application/x-bzip2", fg = "#CD9EFC" },
	{ mime = "application/x-7z-compressed", fg = "#CD9EFC" },
	{ mime = "application/x-rar", fg = "#CD9EFC" },

	# Fallback
	{ name = "*", fg = "#C8D3F8" },
	{ name = "*/", fg = "#80AEFA" }
]

[icons]

"Desktop/"     = ""
"Documents/"   = ""
"Downloads/"   = ""
"Pictures/"    = ""
"Music/"       = ""
"Movies/"      = ""
"Videos/"      = ""
"Public/"      = ""
"Library/"     = ""
"Development/" = ""
".config/"     = ""

# Git
".git/"          = ""
".gitignore"     = ""
".gitmodules"    = ""
".gitattributes" = ""

# Dotfiles
".DS_Store"    = ""
".bashrc"      = ""
".bashprofile" = ""
".zshrc"       = ""
".zshenv"      = ""
".zprofile"    = ""
".vimrc"       = ""

# Text
"*.txt" = ""
"*.md"  = ""

# Archives
"*.zip" = ""
"*.tar" = ""
"*.gz"  = ""
"*.7z"  = ""

# Audio
"*.mp3"  = ""
"*.flac" = ""
"*.wav"  = ""

# Movies
"*.mp4" = ""
"*.mkv" = ""
"*.avi" = ""
"*.mov" = ""

# Images
"*.jpg"  = ""
"*.jpeg" = ""
"*.png"  = ""
"*.gif"  = ""
"*.webp" = ""
"*.avif" = ""
"*.bmp"  = ""
"*.ico"  = ""
"*.svg"  = ""

# Programming
"*.c"     = ""
"*.cpp"   = ""
"*.h"     = ""
"*.hpp"   = ""
"*.rs"    = ""
"*.go"    = ""
"*.py"    = ""
"*.js"    = ""
"*.ts"    = ""
"*.tsx"   = ""
"*.jsx"   = ""
"*.rb"    = ""
"*.php"   = ""
"*.java"  = ""
"*.sh"    = ""
"*.fish"  = ""
"*.swift" = ""
"*.vim"   = ""
"*.lua"   = ""
"*.html"  = ""
"*.css"   = ""
"*.scss"  = ""
"*.json"  = ""
"*.toml"  = ""
"*.yml"   = ""
"*.yaml"  = ""
"*.ini"   = ""
"*.conf"  = ""

# Default
"*"  = ""
"*/" = ""
