[manager]
sort_by      = "modified"
sort_reverse = true
show_hidden  = false

[preview]
tab_size   = 2
max_width  = 600
max_height = 900

[opener]
folder = [
	{ exec = "open -R $*", display_name = "Reveal in Finder" },
	{ exec = "vim $*" },
]
archive = [
	{ exec = "unar $0", display_name = "Extract here" },
]
text = [
	{ exec = "vim $*", block = true },
]
image = [
	{ exec = "open $*", display_name = "Open" },
	{ exec = "exiftool $0", block = true, display_name = "Show EXIF" },
]
video = [
	{ exec = "mpv $*" },
	{ exec = "mediainfo $0", block = true, display_name = "Show media info" },
]
audio = [
	{ exec = "mpv $*" },
	{ exec = "mediainfo $0", block = true, display_name = "Show media info" },
]
fallback = [
	{ exec = "open $*", display_name = "Open" },
	{ exec = "open -R $*", display_name = "Reveal in Finder" },
]

[open]
rules = [
	{ name = "*/", use = "folder" },
	{ name = "*.html", use = "fallback" },

	{ mime = "text/*", use = "text" },
	{ mime = "image/*", use = "image" },
	{ mime = "video/*", use = "video" },
	{ mime = "audio/*", use = "audio" },

	{ mime = "application/x-bzip", use = "archive" },
	{ mime = "application/x-bzip2", use = "archive" },
	{ mime = "application/gzip", use = "archive" },
	{ mime = "application/vnd.rar", use = "archive" },
	{ mime = "application/x-tar", use = "archive" },
	{ mime = "application/zip", use = "archive" },
	{ mime = "application/x-7z-compressed", use = "archive" },
]

[log]
enabled = false
