color = "Never"
condense_wildcard_suffixes = true
edition = "2021"
enum_discrim_align_threshold = 99
fn_single_line = true
format_code_in_doc_comments = false
format_generated_files = false
format_macro_matchers = true
format_macro_bodies = true
format_strings = false
hard_tabs = true
hex_literal_case = "Lower"
hide_parse_errors = true
imports_indent = "Visual"
imports_layout = "Horizontal"
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = false
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
reorder_modules = true
struct_field_align_threshold = 99
tab_spaces = 2
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
version = "Two"
wrap_comments = true
