[package]
name        = "yazi-vfs"
version     = "26.1.4"
edition     = "2024"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi virtual file system"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[lints]
workspace = true

[dependencies]
yazi-config = { path = "../yazi-config", version = "26.1.4" }
yazi-fs     = { path = "../yazi-fs", version = "26.1.4" }
yazi-macro  = { path = "../yazi-macro", version = "26.1.4" }
yazi-sftp   = { path = "../yazi-sftp", version = "26.1.4" }
yazi-shared = { path = "../yazi-shared", version = "26.1.4" }

# External dependencies
anyhow      = { workspace = true }
deadpool    = { version = "0.12.3", default-features = false, features = [ "managed", "rt_tokio_1" ] }
futures     = { workspace = true }
hashbrown   = { workspace = true }
parking_lot = { workspace = true }
russh       = { workspace = true }
tokio       = { workspace = true }
tracing     = { workspace = true }
typed-path  = { workspace = true }
