blank_issues_enabled: false
contact_links:
  - name: ğŸ“ Documentation Improvement
    url: https://github.com/yazi-rs/yazi-rs.github.io
    about: If you'd like to help improve the documentation
  - name: ğŸ’¬ GitHub Discussions
    url: https://github.com/sxyazi/yazi/discussions/new?category=1-q-a
    about: When you have questions that are not bug reports or feature requests
  - name: ğŸŒ Discord Server / Telegram Group
    url: https://github.com/sxyazi/yazi#discussion
    about: If you'd prefer more realtime conversation with the community
