[package]
name        = "yazi-term"
version     = "26.1.22"
edition     = "2024"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi terminal extensions"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[lints]
workspace = true

[dependencies]
yazi-config   = { path = "../yazi-config", version = "26.1.22" }
yazi-emulator = { path = "../yazi-emulator", version = "26.1.22" }
yazi-macro    = { path = "../yazi-macro", version = "26.1.22" }
yazi-shared   = { path = "../yazi-shared", version = "26.1.22" }
yazi-shim     = { path = "../yazi-shim", version = "26.1.22" }
yazi-tty      = { path = "../yazi-tty", version = "26.1.22" }

# External dependencies
anyhow    = { workspace = true }
crossterm = { workspace = true }
ratatui   = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
crossterm = { workspace = true, features = [ "use-dev-tty", "libc" ] }
