[package]
name        = "yazi-core"
version     = "0.2.5"
edition     = "2021"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi core logic"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-adapter   = { path = "../yazi-adapter", version = "0.2.5" }
yazi-boot      = { path = "../yazi-boot", version = "0.2.5" }
yazi-config    = { path = "../yazi-config", version = "0.2.5" }
yazi-dds       = { path = "../yazi-dds", version = "0.2.5" }
yazi-plugin    = { path = "../yazi-plugin", version = "0.2.5" }
yazi-proxy     = { path = "../yazi-proxy", version = "0.2.5" }
yazi-scheduler = { path = "../yazi-scheduler", version = "0.2.5" }
yazi-shared    = { path = "../yazi-shared", version = "0.2.5" }

# External dependencies
anyhow        = "1.0.86"
bitflags      = "2.5.0"
crossterm     = "0.27.0"
dirs          = "5.0.1"
futures       = "0.3.30"
notify        = { version = "6.1.1", default-features = false, features = [ "macos_fsevent" ] }
parking_lot   = "0.12.3"
ratatui       = "0.27.0"
regex         = "1.10.5"
scopeguard    = "1.2.0"
serde         = "1.0.203"
shell-words   = "1.1.0"
tokio         = { version = "1.38.0", features = [ "full" ] }
tokio-stream  = "0.1.15"
tokio-util    = "0.7.11"
unicode-width = "0.1.13"

# Logging
tracing = { version = "0.1.40", features = [ "max_level_debug", "release_max_level_warn" ] }

[target."cfg(unix)".dependencies]
libc = "0.2.155"
