[package]
name        = "yazi-core"
version     = "0.2.1"
edition     = "2021"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi core logic"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-adaptor   = { path = "../yazi-adaptor", version = "0.2.1" }
yazi-config    = { path = "../yazi-config", version = "0.2.1" }
yazi-plugin    = { path = "../yazi-plugin", version = "0.2.1" }
yazi-scheduler = { path = "../yazi-scheduler", version = "0.2.1" }
yazi-shared    = { path = "../yazi-shared", version = "0.2.1" }

# External dependencies
anyhow        = "^1"
base64        = "^0"
bitflags      = "^2"
crossterm     = "^0"
futures       = "^0"
indexmap      = "^2"
notify        = { version = "^6", default-features = false, features = [ "macos_fsevent" ] }
parking_lot   = "^0"
ratatui       = "^0"
regex         = "^1"
serde         = "^1"
syntect       = { version = "^5", default-features = false, features = [ "parsing", "plist-load", "regex-onig" ] }
tokio         = { version = "^1", features = [ "parking_lot", "macros", "rt-multi-thread", "sync", "time", "fs", "process", "io-std", "io-util" ] }
tokio-stream  = "^0"
tokio-util    = "^0"
unicode-width = "^0"

# Logging
tracing = { version = "^0", features = [ "max_level_debug", "release_max_level_warn" ] }

[target."cfg(unix)".dependencies]
libc = "^0"

[target."cfg(windows)".dependencies]
clipboard-win = "^4"
