[package]
name        = "yazi-core"
version     = "25.12.29"
edition     = "2024"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi core logic"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[lints]
workspace = true

[dependencies]
yazi-adapter   = { path = "../yazi-adapter", version = "25.12.29" }
yazi-config    = { path = "../yazi-config", version = "25.12.29" }
yazi-dds       = { path = "../yazi-dds", version = "25.12.29" }
yazi-fs        = { path = "../yazi-fs", version = "25.12.29" }
yazi-macro     = { path = "../yazi-macro", version = "25.12.29" }
yazi-parser    = { path = "../yazi-parser", version = "25.12.29" }
yazi-plugin    = { path = "../yazi-plugin", version = "25.12.29" }
yazi-proxy     = { path = "../yazi-proxy", version = "25.12.29" }
yazi-scheduler = { path = "../yazi-scheduler", version = "25.12.29" }
yazi-shared    = { path = "../yazi-shared", version = "25.12.29" }
yazi-vfs       = { path = "../yazi-vfs", version = "25.12.29" }
yazi-watcher   = { path = "../yazi-watcher", version = "25.12.29" }
yazi-widgets   = { path = "../yazi-widgets", version = "25.12.29" }

# External dependencies
anyhow        = { workspace = true }
crossterm     = { workspace = true }
hashbrown     = { workspace = true }
indexmap      = { workspace = true }
parking_lot   = { workspace = true }
ratatui       = { workspace = true }
tokio         = { workspace = true }
tokio-stream  = { workspace = true }
tokio-util    = { workspace = true }
tracing       = { workspace = true }
unicode-width = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
crossterm = { workspace = true, features = [ "use-dev-tty", "libc" ] }
