[package]
name        = "yazi-core"
version     = "0.1.5"
edition     = "2021"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi core logic"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-adaptor = { path = "../yazi-adaptor", version = "0.1.5" }
yazi-config  = { path = "../yazi-config", version = "0.1.5" }
yazi-shared  = { path = "../yazi-shared", version = "0.1.5" }

# External dependencies
anyhow        = "^1"
async-channel = "^1"
crossterm     = "^0"
futures       = "^0"
indexmap      = "^2"
libc          = "^0"
notify        = { version = "^6", default-features = false, features = [ "macos_fsevent" ] }
parking_lot   = "^0"
ratatui       = "^0"
regex         = "^1"
serde         = "^1"
serde_json    = "^1"
syntect       = "^5"
tokio         = { version = "^1", features = [ "parking_lot", "macros", "rt-multi-thread", "sync", "time", "fs", "process", "io-std", "io-util" ] }
tokio-stream  = "^0"
trash         = "^3"
unicode-width = "^0"
yazi-prebuild = "^0"

# Logging
tracing = { version = "^0", features = [ "max_level_debug", "release_max_level_warn" ] }

[target."cfg(windows)".dependencies]
clipboard-win = "^4"
