[package]
name        = "yazi-core"
version     = "25.5.31"
edition     = "2024"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi core logic"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-adapter   = { path = "../yazi-adapter", version = "25.5.31" }
yazi-boot      = { path = "../yazi-boot", version = "25.5.31" }
yazi-codegen   = { path = "../yazi-codegen", version = "25.5.31" }
yazi-config    = { path = "../yazi-config", version = "25.5.31" }
yazi-dds       = { path = "../yazi-dds", version = "25.5.31" }
yazi-fs        = { path = "../yazi-fs", version = "25.5.31" }
yazi-macro     = { path = "../yazi-macro", version = "25.5.31" }
yazi-plugin    = { path = "../yazi-plugin", version = "25.5.31" }
yazi-proxy     = { path = "../yazi-proxy", version = "25.5.31" }
yazi-scheduler = { path = "../yazi-scheduler", version = "25.5.31" }
yazi-shared    = { path = "../yazi-shared", version = "25.5.31" }
yazi-term      = { path = "../yazi-term", version = "25.5.31" }
yazi-widgets   = { path = "../yazi-widgets", version = "25.5.31" }

# External dependencies
anyhow        = { workspace = true }
bitflags      = { workspace = true }
crossterm     = { workspace = true }
dirs          = { workspace = true }
futures       = { workspace = true }
indexmap      = { workspace = true }
notify        = { version = "8.0.0", default-features = false, features = [ "macos_fsevent" ] }
parking_lot   = { workspace = true }
ratatui       = { workspace = true }
scopeguard    = { workspace = true }
serde         = { workspace = true }
tokio         = { workspace = true }
tokio-stream  = { workspace = true }
tokio-util    = { workspace = true }
tracing       = { workspace = true }
unicode-width = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
crossterm = { workspace = true, features = [ "use-dev-tty", "libc" ] }
