[package]
name        = "yazi-scheduler"
version     = "25.5.31"
edition     = "2024"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi task scheduler"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-config = { path = "../yazi-config", version = "25.5.31" }
yazi-dds    = { path = "../yazi-dds", version = "25.5.31" }
yazi-fs     = { path = "../yazi-fs", version = "25.5.31" }
yazi-macro  = { path = "../yazi-macro", version = "25.5.31" }
yazi-plugin = { path = "../yazi-plugin", version = "25.5.31" }
yazi-proxy  = { path = "../yazi-proxy", version = "25.5.31" }
yazi-shared = { path = "../yazi-shared", version = "25.5.31" }

# External dependencies
anyhow                 = { workspace = true }
async-priority-channel = "0.2.0"
futures                = { workspace = true }
lru                    = { workspace = true }
parking_lot            = { workspace = true }
scopeguard             = { workspace = true }
tokio                  = { workspace = true }
tracing                = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }

[target.'cfg(not(target_os = "android"))'.dependencies]
trash = "5.2.2"
