[package]
name        = "yazi-scheduler"
version     = "0.1.5"
edition     = "2021"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi task scheduler"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-adaptor = { path = "../yazi-adaptor", version = "0.1.5" }
yazi-config  = { path = "../yazi-config", version = "0.1.5" }
yazi-shared  = { path = "../yazi-shared", version = "0.1.5" }

# External dependencies
anyhow        = "^1"
async-channel = "^1"
base64        = "^0"
crossterm     = "^0"
futures       = "^0"
libc          = "^0"
parking_lot   = "^0"
regex         = "^1"
serde         = "^1"
serde_json    = "^1"
tokio         = { version = "^1", features = [ "parking_lot", "rt-multi-thread" ] }
trash         = "^3"

# Logging
tracing = { version = "^0", features = [ "max_level_debug", "release_max_level_warn" ] }
