[package]
name        = "yazi-scheduler"
version     = "25.9.15"
edition     = "2024"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi task scheduler"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-config = { path = "../yazi-config", version = "25.9.15" }
yazi-dds    = { path = "../yazi-dds", version = "25.9.15" }
yazi-fs     = { path = "../yazi-fs", version = "25.9.15" }
yazi-macro  = { path = "../yazi-macro", version = "25.9.15" }
yazi-parser = { path = "../yazi-parser", version = "25.9.15" }
yazi-plugin = { path = "../yazi-plugin", version = "25.9.15" }
yazi-proxy  = { path = "../yazi-proxy", version = "25.9.15" }
yazi-shared = { path = "../yazi-shared", version = "25.9.15" }

# External dependencies
anyhow                 = { workspace = true }
async-priority-channel = "0.2.0"
futures                = { workspace = true }
hashbrown              = { workspace = true }
lru                    = { workspace = true }
mlua                   = { workspace = true }
ordered-float          = { workspace = true }
parking_lot            = { workspace = true }
scopeguard             = { workspace = true }
serde                  = { workspace = true }
tokio                  = { workspace = true }
tokio-util             = { workspace = true }
tracing                = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }
