[package]
name        = "yazi-scheduler"
version     = "0.2.5"
edition     = "2021"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi task scheduler"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-config = { path = "../yazi-config", version = "0.2.5" }
yazi-dds    = { path = "../yazi-dds", version = "0.2.5" }
yazi-plugin = { path = "../yazi-plugin", version = "0.2.5" }
yazi-proxy  = { path = "../yazi-proxy", version = "0.2.5" }
yazi-shared = { path = "../yazi-shared", version = "0.2.5" }

# External dependencies
anyhow                 = "1.0.86"
async-priority-channel = "0.2.0"
futures                = "0.3.30"
parking_lot            = "0.12.3"
scopeguard             = "1.2.0"
tokio                  = { version = "1.38.0", features = [ "full" ] }

# Logging
tracing = { version = "0.1.40", features = [ "max_level_debug", "release_max_level_warn" ] }

[target."cfg(unix)".dependencies]
libc = "0.2.155"

[target.'cfg(not(target_os = "android"))'.dependencies]
trash = "5.0.0"
