[package]
name         = "yazi-shared"
version      = "25.6.11"
edition      = "2024"
license      = "MIT"
authors      = [ "sxyazi <sxyazi@gmail.com>" ]
description  = "Yazi shared library"
homepage     = "https://yazi-rs.github.io"
repository   = "https://github.com/sxyazi/yazi"
rust-version = "1.87.0"

[dependencies]
yazi-macro = { path = "../yazi-macro", version = "25.6.11" }

# External dependencies
anyhow           = { workspace = true }
crossterm        = { workspace = true }
foldhash         = { workspace = true }
futures          = { workspace = true }
memchr           = "2.7.5"
ordered-float    = { workspace = true }
parking_lot      = { workspace = true }
percent-encoding = "2.3.1"
serde            = { workspace = true }
tokio            = { workspace = true }

[target."cfg(unix)".dependencies]
libc  = { workspace = true }
uzers = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.60.2", features = [ "Win32_UI_Shell" ] }

[target.'cfg(target_os = "macos")'.dependencies]
crossterm = { workspace = true, features = [ "use-dev-tty", "libc" ] }
