[package]
name        = "yazi-fs"
version     = "0.4.3"
edition     = "2021"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi file system"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-macro  = { path = "../yazi-macro", version = "0.4.3" }
yazi-shared = { path = "../yazi-shared", version = "0.4.3" }

# External dependencies
anyhow   = { workspace = true }
arc-swap = "1.7.1"
bitflags = { workspace = true }
dirs     = { workspace = true }
futures  = { workspace = true }
regex    = { workspace = true }
serde    = { workspace = true }
tokio    = { workspace = true }

[target."cfg(unix)".dependencies]
libc  = { workspace = true }
uzers = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59.0", features = [ "Win32_Storage_FileSystem" ] }
