[package]
name        = "yazi-config"
version     = "0.2.5"
edition     = "2021"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi configuration file parser"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-shared = { path = "../yazi-shared", version = "0.2.5" }

# External dependencies
anyhow      = "1.0.86"
arc-swap    = "1.7.1"
bitflags    = "2.5.0"
crossterm   = "0.27.0"
globset     = "0.4.14"
indexmap    = "2.2.6"
ratatui     = "0.26.3"
serde       = { version = "1.0.203", features = [ "derive" ] }
toml        = { version = "0.8.14", features = [ "preserve_order" ] }
validator   = { version = "0.18.1", features = [ "derive" ] }
