[package]
name        = "yazi-config"
version     = "25.3.2"
edition     = "2021"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi configuration file parser"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-fs     = { path = "../yazi-fs", version = "25.3.2" }
yazi-macro  = { path = "../yazi-macro", version = "25.3.2" }
yazi-shared = { path = "../yazi-shared", version = "25.3.2" }

# External dependencies
anyhow    = { workspace = true }
bitflags  = { workspace = true }
crossterm = { workspace = true }
globset   = { workspace = true }
indexmap  = { workspace = true }
ratatui   = { workspace = true }
regex     = { workspace = true }
serde     = { workspace = true }
toml      = { workspace = true }
tracing   = { workspace = true }
validator = { version = "0.20.0", features = [ "derive" ] }

[target.'cfg(target_os = "macos")'.dependencies]
crossterm = { workspace = true, features = [ "use-dev-tty", "libc" ] }
