[package]
name        = "yazi-proxy"
version     = "26.1.4"
edition     = "2024"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi event proxy"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[lints]
workspace = true

[dependencies]
yazi-config = { path = "../yazi-config", version = "26.1.4" }
yazi-macro  = { path = "../yazi-macro", version = "26.1.4" }
yazi-parser = { path = "../yazi-parser", version = "26.1.4" }
yazi-shared = { path = "../yazi-shared", version = "26.1.4" }

# External dependencies
anyhow = { workspace = true }
tokio  = { workspace = true }
