[package]
name        = "yazi-proxy"
version     = "25.6.11"
edition     = "2024"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi event proxy"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[features]
default      = [ "vendored-lua" ]
vendored-lua = [ "mlua/vendored" ]

[dependencies]
yazi-config = { path = "../yazi-config", version = "25.6.11" }
yazi-macro  = { path = "../yazi-macro", version = "25.6.11" }
yazi-shared = { path = "../yazi-shared", version = "25.6.11" }

# External dependencies
anyhow = { workspace = true }
mlua   = { workspace = true }
serde  = { workspace = true }
tokio  = { workspace = true }
