[package]
name        = "yazi-proxy"
version     = "0.3.3"
edition     = "2021"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi event proxy"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[features]
default      = [ "vendored-lua" ]
vendored-lua = [ "mlua/vendored" ]

[dependencies]
yazi-config = { path = "../yazi-config", version = "0.3.3" }
yazi-shared = { path = "../yazi-shared", version = "0.3.3" }

# External dependencies
anyhow      = { workspace = true }
mlua        = { workspace = true }
shell-words = { workspace = true }
tokio       = { workspace = true }
