[package]
name        = "yazi-watcher"
version     = "26.1.4"
edition     = "2024"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi file watcher"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[lints]
workspace = true

[dependencies]
yazi-adapter = { path = "../yazi-adapter", version = "26.1.4" }
yazi-dds     = { path = "../yazi-dds", version = "26.1.4" }
yazi-fs      = { path = "../yazi-fs", version = "26.1.4" }
yazi-macro   = { path = "../yazi-macro", version = "26.1.4" }
yazi-proxy   = { path = "../yazi-proxy", version = "26.1.4" }
yazi-shared  = { path = "../yazi-shared", version = "26.1.4" }
yazi-vfs     = { path = "../yazi-vfs", version = "26.1.4" }

# Logging
tracing = { workspace = true }

# External dependencies
anyhow           = { workspace = true }
hashbrown        = { workspace = true }
notify           = { version = "8.2.0", default-features = false, features = [ "macos_fsevent" ] }
parking_lot      = { workspace = true }
percent-encoding = { workspace = true }
tokio            = { workspace = true }
tokio-stream     = { workspace = true }
