[package]
name        = "yazi-boot"
version     = "0.4.3"
edition     = "2021"
license     = "MIT"
authors     = [ "sxyazi <sxyazi@gmail.com>" ]
description = "Yazi bootstrapper"
homepage    = "https://yazi-rs.github.io"
repository  = "https://github.com/sxyazi/yazi"

[dependencies]
yazi-adapter = { path = "../yazi-adapter", version = "0.4.3" }
yazi-config  = { path = "../yazi-config", version = "0.4.3" }
yazi-fs      = { path = "../yazi-fs", version = "0.4.3" }
yazi-macro   = { path = "../yazi-macro", version = "0.4.3" }
yazi-shared  = { path = "../yazi-shared", version = "0.4.3" }

# External dependencies
clap  = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }

[build-dependencies]
clap                  = { workspace = true }
clap_complete         = "4.5.40"
clap_complete_fig     = "4.5.2"
clap_complete_nushell = "4.5.4"
vergen-gitcl          = { version = "1.0.2", features = [ "build", "rustc" ] }
